/* Generated by Amaranth Yosys 0.40 (PyPI ver 0.40.0.0.post101, git sha1 a1bb0255d) */

(* top =  1  *)
(* src = "C:\\my\\vatsa\\design\\hdl\\yatra\\up_counter.py:32" *)
(* generator = "Amaranth" *)
module top(clk, rst, ovf, en);
  reg \$auto$verilog_backend.cc:2352:dump_module$1  = 0;
  wire [16:0] \$1 ;
  reg [15:0] \$2 ;
  (* src = "C:\\Users\\vatsa\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\amaranth\\hdl\\_ir.py:283" *)
  input clk;
  wire clk;
  (* src = "C:\\my\\vatsa\\design\\hdl\\yatra\\up_counter.py:29" *)
  reg [15:0] count = 16'h0000;
  (* src = "C:\\my\\vatsa\\design\\hdl\\yatra\\up_counter.py:25" *)
  input en;
  wire en;
  (* src = "C:\\my\\vatsa\\design\\hdl\\yatra\\up_counter.py:26" *)
  output ovf;
  wire ovf;
  (* src = "C:\\Users\\vatsa\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\amaranth\\hdl\\_ir.py:283" *)
  input rst;
  wire rst;
  assign ovf = count == (* src = "C:\\my\\vatsa\\design\\hdl\\yatra\\up_counter.py:34" *) 5'h19;
  assign \$1  = count + (* src = "C:\\my\\vatsa\\design\\hdl\\yatra\\up_counter.py:40" *) 1'h1;
  (* src = "C:\\my\\vatsa\\design\\hdl\\yatra\\up_counter.py:29" *)
  always @(posedge clk)
    count <= \$2 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$2  = count;
    if (en) begin
      (* full_case = 32'd1 *)
      if (ovf) begin
        \$2  = 16'h0000;
      end else begin
        \$2  = \$1 [15:0];
      end
    end
    if (rst) begin
      \$2  = 16'h0000;
    end
  end
endmodule
